version: '3.8'

services:
  notificaciones-service:
    build: .
    ports:
      - "8083:8083"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: notificaciones_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: gorilla.lmq.cloudamqp.com
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: wmjcvznb
      RABBITMQ_PASSWORD: kajL4rdiURb0bd1U2X7dFt_FQlCGoYkR
      RABBITMQ_VHOST: wmjcvznb
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: notificaciones_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"