spring.application.name=notificaciones-service
server.port=8083

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:notificaciones_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:gorilla.lmq.cloudamqp.com}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:wmjcvznb}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:kajL4rdiURb0bd1U2X7dFt_FQlCGoYkR}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:wmjcvznb}

# JWT
jwt.secret=thisisaverylongsecretkeyforjwkeyfornotificaciones

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always