spring.application.name=notificaciones-service
server.port=8083

# PostgreSQL
spring.datasource.url=${DB_URL:localhost}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:gorilla.lmq.cloudamqp.com}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:wmjcvznb}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:kajL4rdiURb0bd1U2X7dFt_FQlCGoYkR}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:wmjcvznb}

# JWT
jwt.secret=${JWT_SECRET:ESTERNOCLEIDOMASTOIDEO_ACIDODESOXIRRIBONUCLEICO_ACIDORIBONUCLEICO}

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Limitar conexiones HikariCP
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

# RabbitMQ retry
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=3000
spring.rabbitmq.listener.simple.retry.max-attempts=5
spring.rabbitmq.listener.simple.retry.max-interval=10000
spring.rabbitmq.listener.simple.retry.multiplier=2